name = "MiniThesis"
uuid = "5a0628fe-1738-4658-9b6d-0b7605a9755b"
authors = ["Sukera <Seelengrab@users.noreply.github.com> and contributors"]
version = "0.1.0-DEV"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Logging = "1.6"
Random = "1.6"
julia = "1.6"
